# 외부 파일에서 데이터 읽어서 사용하기
### numpy module, loadtxt 등의 메소드 사용

In [73]:
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_eager_execution()

xy = np.loadtxt('0_data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[ : , 0:-1]
y_data = xy[ : ,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [74]:
X = tf.placeholder(tf.float32, shape = [None,3])
Y = tf.placeholder(tf.float32, shape = [None,1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [75]:
hypothesis = tf.matmul(x, W)
cost = tf.reduce_mean(tf.square(hypothesis-y))

In [76]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [77]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [78]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict = {X: x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "\ncost : ", cost_val, "\nprediction : ", hy_val)
        
        print("Your score will be : ", sess.run(hypothesis, feed_dict={X: [[80,100,90]]})) # 학습될 때마다 score가 달라짐

0 
cost :  1158.13 
prediction :  [[156.64847 ]
 [191.58429 ]
 [187.14066 ]
 [202.92055 ]
 [147.6688  ]
 [107.879135]
 [149.63754 ]
 [107.68198 ]
 [178.7266  ]
 [163.86955 ]
 [146.06851 ]
 [145.1433  ]
 [194.31815 ]
 [163.03668 ]
 [150.72049 ]
 [193.25699 ]
 [157.38062 ]
 [178.25104 ]
 [184.88704 ]
 [164.90892 ]
 [176.267   ]
 [178.6477  ]
 [168.03067 ]
 [160.17805 ]
 [198.45926 ]]
Your score will be :  [[153.89627]
 [188.27696]
 [183.88148]
 [199.37231]
 [145.1456 ]
 [106.0209 ]
 [146.98325]
 [105.71658]
 [175.63733]
 [161.01093]
 [143.51015]
 [142.62144]
 [190.9497 ]
 [160.23486]
 [148.05423]
 [189.90195]
 [154.71092]
 [175.06624]
 [181.67545]
 [162.03548]
 [173.15404]
 [175.54619]
 [165.0623 ]
 [157.40027]
 [195.03091]]
500 
cost :  1090.9023 
prediction :  [[149.26219]
 [182.93141]
 [178.45317]
 [194.0177 ]
 [140.66461]
 [103.60338]
 [143.74121]
 [104.37749]
 [171.37447]
 [158.31448]
 [139.88098]
 [139.35565]
 [184.7736 ]
 [154.31726]
 [144.89246]
 [184.98828]
 [148.4675 ]
 [171.47